# Generated by Django 5.2.1 on 2025-06-22 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_seed_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="id_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.roles",
            ),
        ),
    ]
