# Generated by Django 5.2.1 on 2025-06-22 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hardware", "0002_seed_hardware_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="hardware",
            old_name="category_id",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="hardwarehistory",
            old_name="hardware_id",
            new_name="hardware",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="supervisor_id",
            new_name="supervisor",
        ),
        migrations.RemoveField(
            model_name="hardware",
            name="project_id",
        ),
        migrations.RemoveField(
            model_name="hardware",
            name="user_id",
        ),
        migrations.AddField(
            model_name="hardware",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hardware.project",
            ),
        ),
        migrations.AddField(
            model_name="hardware",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hardwarehistory",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("ASSIGNED", "Assigned to user and/or project"),
                    ("RETURNED", "Returned to storage"),
                    ("REPAIR", "Sent for repair"),
                    ("UTILIZED", "Utilized"),
                    ("CREATED", "Created"),
                ],
                default="CREATED",
                max_length=10,
            ),
        ),
    ]
