# Generated by Django 5.2.1 on 2025-06-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("licenses", "0003_seed_software_licenses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="software",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="software",
            name="producer",
            field=models.CharField(max_length=100),
        ),
    ]
