# Generated by Django 5.2.1 on 2025-06-22 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("licenses", "0004_alter_software_name_alter_software_producer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="license",
            old_name="software_id",
            new_name="software",
        ),
        migrations.RenameField(
            model_name="license",
            old_name="user_id",
            new_name="user",
        ),
    ]
